#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80
EXPOSE 8080
EXPOSE 5432

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["OnlineStore/OnlineStore.csproj", "OnlineStore/"]
COPY ["OnlineStore.Autofac/OnlineStore.Autofac.csproj", "OnlineStore.Autofac/"]
COPY ["OnlineStore.BLL/OnlineStore.BLL.csproj", "OnlineStore.BLL/"]
COPY ["OnlineStore.Configuration/OnlineStore.Configuration.csproj", "OnlineStore.Configuration/"]
COPY ["OnlineStore.DAL/OnlineStore.DAL.csproj", "OnlineStore.DAL/"]
RUN dotnet restore "./OnlineStore/./OnlineStore.csproj"
COPY . .
WORKDIR "/src/OnlineStore"
RUN dotnet build "./OnlineStore.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./OnlineStore.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OnlineStore.dll"]